import { ThemeId } from './types';

const AFFIRMATIONS: Record<ThemeId, string[]> = {
  rich: [
    'Abundance flows to me naturally and effortlessly.',
    'I am worthy of financial freedom and prosperity.',
    'Money is a tool that amplifies the good I do in the world.',
    'I release all resistance to attracting wealth.',
    'My income is constantly increasing.',
    'I am open to receiving abundance in all forms.',
    'Wealth comes to me from expected and unexpected sources.',
    'I deserve to be paid well for my skills and talents.',
    'Financial abundance is my birthright.',
    'I attract opportunities that create more wealth.',
    'My relationship with money is healthy and positive.',
    'I am grateful for the abundance that surrounds me.',
    'Every dollar I spend returns to me multiplied.',
    'I think like a wealthy person and make wise choices.',
    'Prosperity is drawn to me in every area of my life.',
    'I am a magnet for financial blessings.',
    'My wealth allows me to live life on my own terms.',
    'I release old stories about money that no longer serve me.',
    'I am building generational wealth with intention.',
    'The universe supports my financial growth.',
    'I celebrate the success and wealth of others.',
    'My net worth is growing every single day.',
    'I invest in myself and it pays dividends.',
    'Abundance is not something I chase — it is something I attract.',
    'I am financially free and secure.',
    'I trust the process of building lasting wealth.',
    'My mind is focused on solutions and opportunities.',
    'I give generously because I know there is always enough.',
    'Wealth creation is a natural expression of who I am.',
    'I am at peace with my financial journey.',
  ],
  love: [
    'I am worthy of deep, unconditional love.',
    'Love flows through me and touches everyone around me.',
    'I attract loving, supportive relationships effortlessly.',
    'My heart is open to giving and receiving love.',
    'I deserve to be loved exactly as I am.',
    'Every day, my capacity for love grows deeper.',
    'I radiate warmth and compassion to all beings.',
    'The love I give returns to me tenfold.',
    'I release the need to be perfect to be loved.',
    'I am surrounded by people who genuinely care for me.',
    'Love heals every part of me that needs healing.',
    'I choose love over fear in every moment.',
    'My relationships are filled with kindness and respect.',
    'I am a beacon of love in this world.',
    'I forgive freely and love flows more easily.',
    'The right people are drawn into my life at the right time.',
    'I love myself fully and without condition.',
    'My heart knows no limits in its ability to love.',
    'I create deep connections with those around me.',
    'Love is my natural state of being.',
    'I am grateful for every expression of love in my life.',
    'I communicate my feelings with honesty and grace.',
    'I attract a love that feels like home.',
    'My vulnerability is my greatest strength.',
    'I am worthy of passion, tenderness, and devotion.',
    'Every relationship teaches me something beautiful.',
    'I nurture love with patience and understanding.',
    'The more love I give, the more I have.',
    'I am gentle with myself and those I love.',
    'Love is the foundation of everything I build.',
  ],
  health: [
    'My body is strong, healthy, and full of energy.',
    'I honor my body with nourishing food and movement.',
    'Every cell in my body vibrates with vitality.',
    'I listen to my body and give it what it needs.',
    'My immune system is powerful and resilient.',
    'I am grateful for the miracle of my body.',
    'Health and wellness flow through me naturally.',
    'I choose thoughts that support my physical wellbeing.',
    'My body heals quickly and efficiently.',
    'I deserve to feel vibrant and alive every day.',
    'Rest is not laziness — it is essential self-care.',
    'I breathe in healing energy with every breath.',
    'My mind and body work together in perfect harmony.',
    'I release tension and embrace deep relaxation.',
    'Every day I grow stronger and more resilient.',
    'I am in tune with the wisdom of my body.',
    'Movement brings me joy and vitality.',
    'I nourish my body, mind, and spirit equally.',
    'My sleep is deep, restorative, and peaceful.',
    'I radiate health and inspire others to thrive.',
    'I trust my body to find balance naturally.',
    'My energy levels increase throughout the day.',
    'I make choices that support my long-term wellbeing.',
    'I am patient with my body as it heals and grows.',
    'Wellness is my natural state of being.',
    'I celebrate every step of my health journey.',
    'My body is a temple and I treat it with reverence.',
    'I release habits that no longer serve my health.',
    'Fresh air, clean water, and whole foods energize me.',
    'I am becoming the healthiest version of myself.',
  ],
  confidence: [
    'I believe in myself and my abilities completely.',
    'I am enough, exactly as I am right now.',
    'My confidence grows stronger with every challenge I face.',
    'I trust myself to make the right decisions.',
    'I stand tall and speak my truth with courage.',
    'My inner strength is limitless.',
    'I am capable of achieving extraordinary things.',
    'I release self-doubt and embrace self-assurance.',
    'My voice matters and deserves to be heard.',
    'I face each day with certainty and poise.',
    'I am comfortable being the center of attention.',
    'My unique qualities make me irreplaceable.',
    'I handle difficult situations with grace and composure.',
    'I am proud of who I am becoming.',
    'Criticism does not define me — my actions do.',
    'I radiate confidence in everything I do.',
    'I am bold, courageous, and unafraid.',
    'My self-worth is not determined by others.',
    'I take up space unapologetically.',
    'Every setback is a setup for a comeback.',
    'I trust my instincts and follow my intuition.',
    'I am worthy of success, respect, and admiration.',
    'My presence commands attention naturally.',
    'I celebrate my strengths and accept my imperfections.',
    'Fear is just excitement without breath — I breathe deeply.',
    'I walk into every room knowing I belong.',
    'My potential is unlimited and my future is bright.',
    'I am the architect of my own confidence.',
    'I choose courage over comfort, always.',
    'I am a force of nature — unstoppable and free.',
  ],
  adventure: [
    'Life is an adventure and I embrace every moment.',
    'I step outside my comfort zone with excitement.',
    'The world is full of wonders waiting for me to discover.',
    'I am open to new experiences and possibilities.',
    'Every day brings a chance to explore something new.',
    'I trust the journey, even when I cannot see the path.',
    'My spirit is wild, free, and full of wonder.',
    'I say yes to life and all its adventures.',
    'The unknown excites me rather than frightens me.',
    'I collect experiences, not things.',
    'Every challenge is an adventure in disguise.',
    'I am brave enough to write my own story.',
    'Nature renews my spirit and fuels my curiosity.',
    'I live boldly and without regret.',
    'The best is yet to come and I am ready for it.',
    'I find magic in the ordinary moments.',
    'My life is a magnificent journey of discovery.',
    'I am designed for exploration and growth.',
    'I release the need for certainty and embrace the mystery.',
    'Every sunrise is an invitation to begin again.',
    'I am the hero of my own adventure.',
    'Curiosity is my compass and courage is my guide.',
    'I travel light and love deeply.',
    'The world opens its doors to those who dare to knock.',
    'I find freedom in movement and peace in stillness.',
    'My adventurous spirit inspires those around me.',
    'I welcome change as the gateway to growth.',
    'Every path I walk becomes an extraordinary journey.',
    'I am alive, awake, and ready for what comes next.',
    'The greatest adventure is the one within.',
  ],
  family: [
    'My family is my greatest source of strength.',
    'I create a home filled with love, laughter, and safety.',
    'I am a positive influence on those I love.',
    'My family bonds grow stronger every day.',
    'I am present and engaged with the people who matter most.',
    'Home is wherever my loved ones are.',
    'I nurture my relationships with patience and devotion.',
    'I am grateful for every moment shared with family.',
    'I build traditions that will be cherished for generations.',
    'My love provides a safe haven for my family.',
    'I listen deeply to understand those I care about.',
    'I lead my family with wisdom, kindness, and integrity.',
    'Every family member is valued and seen.',
    'I forgive and heal, keeping my family bonds strong.',
    'I am building a legacy of love and connection.',
    'Quality time with family is my greatest investment.',
    'I communicate openly and honestly with those I love.',
    'My home is a sanctuary of peace and warmth.',
    'I celebrate the unique gifts each family member brings.',
    'I choose connection over perfection in my family life.',
    'My children feel loved, safe, and empowered.',
    'I honor the wisdom of those who came before me.',
    'I am the kind of family member I wish to have.',
    'Every meal shared together strengthens our bond.',
    'I make space for joy in our everyday routines.',
    'My family knows they can count on me, always.',
    'I balance giving and receiving love within my family.',
    'Our differences make our family beautifully unique.',
    'I am writing a family story worth telling.',
    'Love is the thread that holds us all together.',
  ],
  purpose: [
    'I am exactly where I need to be on my journey.',
    'My life has deep meaning and purpose.',
    'I trust that everything unfolds for a reason.',
    'I am aligned with my highest calling.',
    'My purpose reveals itself more clearly each day.',
    'I make a meaningful difference in the world.',
    'I live with intention and act with purpose.',
    'My unique gifts are needed in this world.',
    'I am guided by a vision greater than myself.',
    'Every experience shapes me into who I am meant to be.',
    'I follow my inner compass with unwavering faith.',
    'My existence is not an accident — it is a gift.',
    'I contribute something that no one else can.',
    'I am connected to something vast and beautiful.',
    'My purpose and passion are one and the same.',
    'I wake each morning with clarity and direction.',
    'The universe conspires to help me fulfill my mission.',
    'I am a vessel for something extraordinary.',
    'My daily actions align with my deepest values.',
    'I leave the world better than I found it.',
    'Meaning is not found — it is created through my choices.',
    'I am called to serve and I answer with joy.',
    'My life is a work of art still being painted.',
    'I trust the timing of my unfolding purpose.',
    'I see the sacred in the mundane.',
    'My legacy is built one intentional moment at a time.',
    'I am becoming the person I was born to be.',
    'Purpose flows through me like a river — steady and sure.',
    'I honor my journey by staying true to my path.',
    'I am here for a reason, and that reason matters.',
  ],
  career: [
    'My career is a reflection of my greatest strengths.',
    'I bring value and excellence to everything I do.',
    'Success is my natural outcome when I show up fully.',
    'I am respected and valued in my professional life.',
    'My skills are in high demand and constantly growing.',
    'I attract opportunities that align with my ambitions.',
    'I work with purpose, focus, and determination.',
    'My professional growth knows no ceiling.',
    'I am a leader, whether or not I hold the title.',
    'I create results that speak for themselves.',
    'I handle pressure with calm and clarity.',
    'My network is filled with people who uplift and support me.',
    'I am not afraid to ask for what I deserve.',
    'Every project I touch benefits from my involvement.',
    'I balance ambition with well-being gracefully.',
    'My career path is uniquely mine and I own it.',
    'I learn from setbacks and grow from every experience.',
    'I am building something meaningful with my work.',
    'Doors open for me because of the value I provide.',
    'I am a master of my craft and still a student of life.',
    'I negotiate with confidence and fairness.',
    'My work ethic inspires those around me.',
    'I set goals that stretch me and then I surpass them.',
    'I am exactly the kind of professional the world needs.',
    'Success and fulfillment coexist in my career.',
    'I embrace feedback as fuel for my growth.',
    'My career supports the life I want to live.',
    'I make bold moves that advance my vision.',
    'I celebrate my professional wins, big and small.',
    'My best work is still ahead of me.',
  ],
};

export function getAffirmations(themeId: ThemeId): string[] {
  return AFFIRMATIONS[themeId];
}

export function getShuffledAffirmations(themeId: ThemeId): string[] {
  const arr = [...AFFIRMATIONS[themeId]];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}
